/*!
 * /**
 * * @file server-rspack.js
 * * @description No code generated
 * * --------------------------------------------------------------------------
 * * ⚡ Rspack Server App (Development)
 * * --------------------------------------------------------------------------
 * * • [   server-entry.js ] ──▶ [■ server-rspack.js ] ──▶ [   server-meteor.js ]
 * *
 * * This file is empty because `meteor.mainModule.server` is not set in package.json.
 * *
 * * ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
 * * These files also act as a cache: they can be safely removed and will be
 * * regenerated on the next build. They should be ignored in IDE suggestions
 * * and version control.
 * * /
 *
 *
 *
 */
(() => {
"use strict";
var __webpack_modules__ = ({
"./server/main.js"(__unused_rspack_module, __unused_rspack___webpack_exports__, __webpack_require__) {
/* import */ var meteor_meteor__rspack_import_0 = __webpack_require__("meteor/meteor");
/* import */ var meteor_meteor__rspack_import_0_default = /*#__PURE__*/__webpack_require__.n(meteor_meteor__rspack_import_0);
/* import */ var meteor_mongo__rspack_import_1 = __webpack_require__("meteor/mongo");
/* import */ var meteor_mongo__rspack_import_1_default = /*#__PURE__*/__webpack_require__.n(meteor_mongo__rspack_import_1);
function asyncGeneratorStep(gen, resolve, reject, _next, _throw, key, arg) {
    try {
        var info = gen[key](arg);
        var value = info.value;
    } catch (error) {
        reject(error);
        return;
    }
    if (info.done) {
        resolve(value);
    } else {
        Promise.resolve(value).then(_next, _throw);
    }
}
function _async_to_generator(fn) {
    return function() {
        var self = this, args = arguments;
        return new Promise(function(resolve, reject) {
            var gen = fn.apply(self, args);
            function _next(value) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "next", value);
            }
            function _throw(err) {
                asyncGeneratorStep(gen, resolve, reject, _next, _throw, "throw", err);
            }
            _next(undefined);
        });
    };
}


/**
 * Reproduction for the Meteor 3.5 change-stream restart loop after
 * ChangeStreamHistoryLost (error 286).
 *
 * Steps (driven by UI buttons calling the methods below):
 *   1. Startup opens an observe on `quiet`, so SharedChangeStream watches it.
 *   2. repro.insertQuiet — one change event, so the driver stores a resume token.
 *   3. repro.rollOplog — bulk-writes to `noise` until the oldest oplog entry is
 *      newer than the stored token (the dev mongo oplog is only 8MB).
 *   4. repro.killCursor — kills the change-stream cursor server-side, forcing a
 *      resume attempt with the now-unresumable token → infinite 286 loop in the
 *      server console.
 */ const Quiet = new meteor_mongo__rspack_import_1.Mongo.Collection('quiet');
const Noise = new meteor_mongo__rspack_import_1.Mongo.Collection('noise');
const driver = meteor_mongo__rspack_import_1.MongoInternals.defaultRemoteCollectionDriver();
const db = driver.mongo.db;
const client = driver.mongo.client;
// Wall-clock seconds of the last quiet insert; compared against oplog
// timestamps (whose high bits are a unix-seconds value) in repro.status.
let lastQuietInsertSec = null;
let observedEvents = 0;
meteor_meteor__rspack_import_0.Meteor.startup(()=>_async_to_generator(function*() {
        yield Quiet.find().observeChangesAsync({
            added () {
                observedEvents++;
            },
            changed () {
                observedEvents++;
            },
            removed () {
                observedEvents++;
            }
        });
        console.log('[repro] observe started on `quiet` — change stream is open');
    })());
function oldestOplogTs() {
    return _async_to_generator(function*() {
        var _ref;
        const [entry] = yield client.db('local').collection('oplog.rs').find({}, {
            projection: {
                ts: 1
            }
        }).sort({
            $natural: 1
        }).limit(1).toArray();
        return (_ref = entry === null || entry === void 0 ? void 0 : entry.ts) !== null && _ref !== void 0 ? _ref : null;
    })();
}
function tsSeconds(ts) {
    return ts ? ts.getHighBits() : null;
}
function findChangeStreamOps() {
    return _async_to_generator(function*() {
        return client.db('admin').aggregate([
            {
                $currentOp: {
                    idleCursors: true,
                    allUsers: true
                }
            },
            {
                $match: {
                    ns: `${db.databaseName}.quiet`,
                    'cursor.originatingCommand.pipeline.0.$changeStream': {
                        $exists: true
                    }
                }
            }
        ]).toArray();
    })();
}
meteor_meteor__rspack_import_0.Meteor.methods({
    'repro.status' () {
        return _async_to_generator(function*() {
            const ts = yield oldestOplogTs();
            const streamOps = yield findChangeStreamOps();
            return {
                dbName: db.databaseName,
                observedEvents,
                lastQuietInsertSec,
                oldestOplogSec: tsSeconds(ts),
                tokenRolledOut: lastQuietInsertSec !== null && tsSeconds(ts) > lastQuietInsertSec,
                changeStreamCursors: streamOps.map((op)=>String(op.cursor.cursorId)),
                noiseCount: yield Noise.find().countAsync()
            };
        })();
    },
    'repro.insertQuiet' () {
        return _async_to_generator(function*() {
            yield Quiet.insertAsync({
                createdAt: new Date()
            });
            lastQuietInsertSec = Math.floor(Date.now() / 1000);
            return {
                insertedAtSec: lastQuietInsertSec
            };
        })();
    },
    'repro.rollOplog' () {
        return _async_to_generator(function*() {
            if (lastQuietInsertSec === null) {
                throw new meteor_meteor__rspack_import_0.Meteor.Error('no-token', 'Insert a quiet doc first (step 2).');
            }
            const big = 'x'.repeat(100000);
            let batches = 0;
            // 8MB dev oplog: each 50-doc batch is ~5MB of churn. WiredTiger truncates
            // the capped oplog lazily on a background thread that only catches up
            // between writes, so pace the batches — a tight loop grows the oplog
            // without ever letting the head get trimmed.
            while(batches < 300){
                const ts = yield oldestOplogTs();
                if (tsSeconds(ts) > lastQuietInsertSec) break;
                yield db.collection('noise').insertMany(Array.from({
                    length: 50
                }, (_, i)=>({
                        i,
                        big
                    })));
                batches++;
                yield new Promise((r)=>setTimeout(r, 250));
            }
            yield db.collection('noise').drop().catch(()=>{});
            const ts = yield oldestOplogTs();
            return {
                batches,
                oldestOplogSec: tsSeconds(ts),
                tokenRolledOut: tsSeconds(ts) > lastQuietInsertSec
            };
        })();
    },
    'repro.killCursor' () {
        return _async_to_generator(function*() {
            var _result_cursorsKilled;
            const ops = yield findChangeStreamOps();
            if (!ops.length) {
                throw new meteor_meteor__rspack_import_0.Meteor.Error('no-cursor', 'No change-stream cursor found on `quiet` — is the observe running?');
            }
            const cursorIds = ops.map((op)=>op.cursor.cursorId);
            const result = yield db.command({
                killCursors: 'quiet',
                cursors: cursorIds
            });
            console.log('[repro] killed change-stream cursor(s):', result);
            return {
                killed: (_result_cursorsKilled = result.cursorsKilled) === null || _result_cursorsKilled === void 0 ? void 0 : _result_cursorsKilled.map(String)
            };
        })();
    }
});
/**
 * Headless driver: with REPRO_AUTO=1 the whole sequence runs on startup and the
 * process prints a machine-readable verdict, so the repro can be checked without
 * the UI buttons. It counts change-stream restart cycles over a window: the bug
 * loops (~10x/sec), a healthy stream restarts at most once and then settles.
 */ if (process.env.REPRO_AUTO === '1') {
    let restartCount = 0;
    let historyLostCount = 0;
    const mentions = (args, needle)=>args.some((a)=>{
            if (a == null) return false;
            if (typeof a === 'string') return a.includes(needle);
            try {
                return JSON.stringify(a).includes(needle);
            } catch (e) {
                return false;
            }
        });
    const origError = console.error;
    console.error = (...args)=>{
        if (mentions(args, 'ChangeStream restart begin')) restartCount++;
        if (mentions(args, '286') || mentions(args, 'ChangeStreamHistoryLost')) {
            historyLostCount++;
        }
        origError.apply(console, args);
    };
    const sleep = (ms)=>new Promise((r)=>setTimeout(r, ms));
    meteor_meteor__rspack_import_0.Meteor.startup(()=>_async_to_generator(function*() {
            try {
                yield sleep(3000);
                console.log('[repro-auto] step 2: insertQuiet');
                console.log('[repro-auto]', (yield meteor_meteor__rspack_import_0.Meteor.callAsync('repro.insertQuiet')));
                console.log('[repro-auto] step 3: rollOplog (~1 min)…');
                console.log('[repro-auto]', (yield meteor_meteor__rspack_import_0.Meteor.callAsync('repro.rollOplog')));
                console.log('[repro-auto] step 4: killCursor');
                console.log('[repro-auto]', (yield meteor_meteor__rspack_import_0.Meteor.callAsync('repro.killCursor')));
                const restartsBefore = restartCount;
                const historyLostBefore = historyLostCount;
                console.log('[repro-auto] observing the stream for 15s…');
                yield sleep(15000);
                const restarts = restartCount - restartsBefore;
                const historyLost = historyLostCount - historyLostBefore;
                const looping = restarts > 3;
                console.log(`[repro-auto] RESULT restarts-in-15s=${restarts} historyLostErrors-in-15s=${historyLost}`);
                console.log(looping ? '[repro-auto] VERDICT: BUG REPRODUCED — change stream is stuck in a restart loop' : '[repro-auto] VERDICT: HEALTHY — change stream recovered, no restart loop');
            } catch (e) {
                console.log('[repro-auto] driver failed:', e && e.message ? e.message : e);
            }
        })());
}


},
"meteor/meteor"(module) {
module.exports = require("meteor/meteor");

},
"meteor/mongo"(module) {
module.exports = require("meteor/mongo");

},

});
// The module cache
var __webpack_module_cache__ = {};

// The require function
function __webpack_require__(moduleId) {

// Check if module is in cache
var cachedModule = __webpack_module_cache__[moduleId];
if (cachedModule !== undefined) {
return cachedModule.exports;
}
// Create a new module (and put it into the cache)
var module = (__webpack_module_cache__[moduleId] = {
exports: {}
});
// Execute the module function
__webpack_modules__[moduleId](module, module.exports, __webpack_require__);

// Return the exports of the module
return module.exports;

}

// webpack/runtime/compat_get_default_export
(() => {
// getDefaultExport function for compatibility with non-ESM modules
__webpack_require__.n = (module) => {
	var getter = module && module.__esModule ?
		() => (module['default']) :
		() => (module);
	__webpack_require__.d(getter, { a: getter });
	return getter;
};

})();
// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = (exports, definition) => {
	for(var key in definition) {
        if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
            Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
        }
    }
};
})();
// webpack/runtime/has_own_property
(() => {
__webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
})();
// webpack/runtime/make_namespace_object
(() => {
// define __esModule on exports
__webpack_require__.r = (exports) => {
	if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
		Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
	}
	Object.defineProperty(exports, '__esModule', { value: true });
};
})();
var __webpack_exports__ = {};
// This entry needs to be wrapped in an IIFE because it needs to be isolated against other modules in the chunk.
(() => {
__webpack_require__.r(__webpack_exports__);
/* import */ var _server_main_js__rspack_import_0 = __webpack_require__("./server/main.js");
/**
* @file server-entry.js
* @description Entry point for Rspack build process
* --------------------------------------------------------------------------
* 🔌 Rspack Server Entry (Development)
* --------------------------------------------------------------------------
* • [■ server-entry.js ] ──▶ [   server-rspack.js ] ──▶ [   server-meteor.js ]
*
* This file is the entry point that Rspack uses to start the build process.
* It imports the module defined in `meteor.mainModule.server` inside package.json.
* From here, Rspack can trace the entire dependency graph of your application
* and generate the bundled output (`server-rspack.js`).
*
* ⚠️ Note: This file is autogenerated. It is not meant to be modified manually.
* These files also act as a cache: they can be safely removed and will be
* regenerated on the next build. They should be ignored in IDE suggestions
* and version control.
*/ /* Link to 🔌 Meteor Server Entry */ 

})();

module.exports = __webpack_exports__;
})()
;
//# sourceMappingURL=server-rspack.js.map